# Generated by Django 4.2.17 on 2024-12-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fields_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fields_3',
        ),
    ]
